config/routes.rb
Rails.application.routes.draw do
  resources :games
  get 'loaned_games' => 'games#loaned_games'
  get 'available_games' => 'games#available_games'
  get 'games/:id/bounty' => 'games#bounty', as: 'bounty'
  post 'return_game/:id' => 'games#return', as: 'return_game' 
  root to: 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  
  def in_stock?
    borrower.length == 0
  end  

  def return_game
    update(borrower: '')
  end  

  def pretty_date
    if date_borrowed
      year, month, day = date_borrowed.split('-').map(&:to_i)
      date = Date.new(year, month, day)
      pretty_date = date.strftime('%B %-d, %Y')
    end
  end  

  def bounty_message
    messages = ['has given in willingly.',
                'was incredibly stubborn so we broke their legs and took the game.',
                "offered their firstborn son to keep this. we told 'em no.",
                'tried running with this, luckily we brought our tazers',
                "was having a date night that we interupted, but that's okay I don't think they were meant for eachother anyway", 
                "fed us cookies so we wouldn't beat 'em up... we did anyways, but only a little :)"]
    messages.sample
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def bounty
    @game = Game.find(params[:id])
    @message = @game.bounty_message
  end  

  def return
    @game = Game.find(params[:id])
    @game.return_game
    redirect_to root_path
  end  

  def loaned_games
    @games = Game.all.select {|game| game.borrower.length > 0}
  end

  def available_games
    @games = Game.all.select {|game| game.borrower.length == 0 }
  end  

  def edit
    @game = Game.find(params[:id])
  end  
    
  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path 
    else
      render :show
    end     
  end  
  
  def show
    @game = Game.find(params[:id])
  end  

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to new_game_path
    else
      render :new  
    end  
  end  

  def destroy
    @game = Game.find(params[:id])
    @game.destroy 
    redirect_to root_path
  end  

  private
  def game_params
    params.require(:game).permit(:id, :title, :borrower, :date_borrowed)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/available_games.html.erb
<% @games.each do |game| %>
  <h2><%= game.title %></h2>
  <%= link_to "View Game", game_path(game), class: "btn btn-primary" %>
  <hr>
<% end %>

app/views/games/bounty.html.erb
<h1> You hire the Mafia.</h1>
<h3>When they return the leader says:</h3><hr>  
<h2>"<%= "#{@game.borrower} #{@message}" %>"</h2><hr>

<%= link_to 'Retrieve Game From Mafia', return_game_path(@game), class: 'btn btn-success', method: :post %>

app/views/games/edit.html.erb
<%= form_for @game do |f| %>
  <h2><%= f.label "Game Name" %><br><h2>
  <%= f.text_field :title %><br><br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/games/index.html.erb
<% @games.each do |game| %>
<h2><%= game.title %></h2>
<h3><%= game.in_stock? ? "This game is in stock" : "Borrowed by #{game.borrower} on #{game.pretty_date}" %></h3>
<%= link_to "View Game", game_path(game.id), class: "btn btn-primary" %>
<hr>
<% end %>

app/views/games/loaned_games.html.erb
<% @games.each do |game| %>
  <h2><%= game.title %></h2>
  <h3><%= "Borrowed by #{game.borrower} on #{game.pretty_date}" %></h3>
  <%= link_to "View Game", game_path(game), class: "btn btn-primary" %>
  <hr>
<% end %>

app/views/games/new.html.erb
<%= form_for @game do |f| %> 
  <%= f.label "Game Name" %><br>
  <%= f.text_field :title %><br><br>
  <%= f.submit "Add Game", class:"btn btn-primary"%><br><br>
<% end %>  

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<% if @game.in_stock? %>
  <h2><%= "This game is in stock" %></h2>
  <%= form_for @game do |f| %>  
    <h3>Not in stock?</h3>
    <h4><%= f.label "This has been borrowed by" %></h4>
    <%= f.text_field :borrower %>
    <h4><%= f.label "On" %></h4>
    <%= f.date_field :date_borrowed %>
    <%= f.submit "Update" %>
  <% end %>  
<% else %>
  <h2><%= "This game has been borrowed by #{@game.borrower} on #{@game.pretty_date}" %><br>
    <%= link_to 'Return Game', return_game_path(@game), class: 'btn btn-success', method: :post %>
    <%= link_to 'Call Mafia', bounty_path(@game), class: 'btn btn-danger' %>
<% end %> 
<br><hr><%= link_to 'Edit Game', edit_game_path(@game), class: 'btn btn-warning' %> 
<%= link_to 'Delete Game', @game, method: :delete, class: 'btn btn-danger' %>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "All Games", games_path, class: "btn" %>
    <%= link_to "Games Loaned", loaned_games_path, class: 'btn' %>
    <%= link_to "Available Games", available_games_path, class: 'btn' %>
    <%= link_to "Add Game", new_game_path, class: 'btn' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
  <div class="jumbotron container">
  <%= yield %>
</div>  
</body>
</html>